### ISSUE TITLE
Powershell scripts

### ISSUE THREAD

**Issue by ioggstream** [randomtable/Sec#1]
Hi, and thanks for your work!

Is it possible to implement such policies with powershell?

**Comment by randomtable** [comment]
Hi and thanks for reply!
Yes is possible, i have uploaded two methods for applying rules with batch or powershell.
You can find scripts and rules in this folders:

For batch:
https://github.com/randomtable/Sec/tree/master/SECBAT

For PowerShell:
https://github.com/randomtable/Sec/tree/master/SECSHELL

Let me know if the scripts are suitable for use, and in case open a new issue!
